### PR TITLE
Use Refgenie for index provision

### PR DESCRIPTION
**Pull request by pinin4fjords**
**(Not to be merged until we confirm s/c analysis move to Codon, but ready for review)**

This PR includes a number of adaptations required to run the control workflows with our new Refgenie indices. Including:

1. A new script to query the Refgenie database and symlink the correct reference files and indices.
2. Rewiring of the control workflow to pass transcriptome indices, rather than raw reference files, to child workflows. 
3. Rewiring of the control workflow to pass a tabular gene annotation file  to tertiary analysis, rather than a GTF

**Note on tertiary analysis change**

3 was triggered by a cascade of ramifications of using pre-built indices from Refgenie:

-  Alevin requires a transcript/ gene mapping synchronised with the cDNA index, which we've previously tackled by pruning cDNA as we index dynamically. However, this was less desirable for a pre-built database of indices, where we'd rather serve resources as they come from Ensembl. 
- The solution was to synchronise transcript and gene annotations with the cDNA rather than vice-versa, deriving annotation from cDNA FASTA headers, but this means that deriving complete annotations requires the presence of both files. 
- Currently, the [tertiary workflow](https://github.com/ebi-gene-expression-group/scxa-workflows/blob/develop/w_smart-seq_clustering/scanpy_clustering_workflow.json)  takes a GTF and uses it to derive metadata in a few forms it needs by running our [GTF handling script (https://github.com/ebi-gene-expression-group/atlas-gene-annotation-manipulation/blob/develop/gtf2featureAnnotation.R) in a few different ways. In the new system we'd have to be passing large cDNA files to the Galaxy workflow to do this, and parsing multiple times. 
- The more efficient solution here is to derive a gene metadata table and pass this directly to the tertiary workflow instead of the GTF. This is also more in line with how we pass cell metadata. 
- All the above to say that we've switched from passing GTF to passing a gene annotation table in order that the more complex derivation of gene-level metadata (including using cDNA headers as a source) can be done only once. 

See related PRs:

- Use metadata from cDNA FASTA headers to synchronise annotations with transcriptomes https://github.com/ebi-gene-expression-group/atlas-gene-annotation-manipulation/pull/1 https://github.com/ebi-gene-expression-group/atlas-gene-annotation-manipulation/pull/2. Also, a move of the Conda recipe to Codon
- Child workflow changes https://github.com/ebi-gene-expression-group/scxa-workflows/pull/25

### CODE REVIEW

**Review by pcm32 — APPROVED** [review]
LGTM

**Comment by pcm32** [comment]
Is the new annotation table file exposed so that it makes it to the FTP, ideally compressed, and then it can be used to reproduce our analysis outside?

**Comment by pinin4fjords** [comment]
> Is the new annotation table file exposed so that it makes it to the FTP, ideally compressed, and then it can be used to reproduce our analysis outside?

Well, it's a product of the GTF and Fasta files that we do publish so it would be a little redundant, but I can add this to that process if you'd like.

**Comment by pcm32** [comment]
I mean, we could remove GTFs if redundant, point would be that the tertiary pipeline has all its input elements readily available for re-analysis from third parties.

**Comment by pinin4fjords** [comment]
Thanks @pcm32 !

**Pull request merged**
