### PR TITLE
Feature/controlled access

### PR DESCRIPTION
**Pull request by pinin4fjords**
Work in progress to allow analysis of controlled access single-cell datasets. These data can only be accessed by the specific permitted user, so quantification of these datasets must be skipped when the the workflow is run by the production user. The user who does have access will run analyses for specific datasets, which will then get picked up as completed bundles (without user-identifiable data) by the production user.

- Add process to skip controlled access datasets for production user
- Supply options to quantification workflows to specify controlled access status and locations for raw data and analysis.

Tested with a smart-seq dataset, works.

Paired with changes in the SMART-seq (https://github.com/ebi-gene-expression-group/scxa-smartseq-quantification-workflow/pull/2) and droplet (https://github.com/ebi-gene-expression-group/scxa-droplet-quantification-workflow/pull/8) workflows.

### CODE REVIEW

**Comment by suhaibMo** [comment]
Excellent work @pinin4fjords for incorporating controlled access for SC.

**Comment by suhaibMo** [comment]
The CA tests worked on Smart-Seq studies. Did you running tests on Droplet-based study ?

**Review by suhaibMo — APPROVED** [review]
LGTM

**Comment by pinin4fjords** [comment]
Thanks @suhaibMo . The implementation is near-identical in droplet. There are likely to be some niggles that pop up when dealing with actual curations that are produced (I had to mock one up here), I will deal with that fallout at that time.

**Pull request merged**
