### PR TITLE
Change SCXA_WORK path to win more disk space

### PR DESCRIPTION
**Pull request by pmb59**
Related to https://github.com/ebi-gene-expression-group/scxa-workflows/pull/37

### CODE REVIEW

**Review by anilthanki — APPROVED** [review]
LGTM

**Comment by anilthanki** [comment]
We need to make sure to delete `$SCXA_WORKFLOW_ROOT/data/work/${workflow}` afterwards or add it as a pipeline step

**Review by irisdianauy — APPROVED** [review]
LGTM

**Comment by pmb59** [comment]
@anilthanki @irisdianauy Thanks for reviewing!

**Pull request merged**
